color:
  saturation: 0.4010372
  brandStrength: 1
  rhythmicContrast: 0.9788214
  brandColors:
    - '#FFFFFF'
    - '#000000'
    - '#545454'
    - '#818181'
    - '#B7B7B7'
  lightness: 0.3296833
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.5114208
typography_spectrum: 0.541573
name: Mellem
